'use strict';

// C1040 — Knowledge Base > Re-Index orchestration.
//
// Backfills every blank/placeholder tag + KB-file description with one generated by
// Claude Opus, reading the actual architecture docs (and, for tags with no doc, a
// sample of task titles that use the tag). Writes BOTH description stores an agent
// can read from:
//   - the DB (`tags.description`, `project_knowledge_files.description`) — what
//     `get_project_tags` / a task-selection agent should query to decide which tags
//     apply to a task, and in turn which KB docs to pull into context;
//   - the `# tt-x — description` H1 line in each `ai/architecture/tt-*.md` — what
//     `list_system_tags` serves locally.
// Only redescribes what's actually broken (null / empty / "Auto-registered..." — see
// C1038) unless `force` is set — a description that already reads real content is
// left alone. Also repairs `tags.knowledge_file_id` — the DB-verified tag<->doc link
// added in migration 046 — whenever it's missing or points at the wrong file, even for
// a tag whose description is already fine (no Opus call needed for a link-only fix).

const fs = require('node:fs');
const path = require('node:path');
const {
  pullArchitectureDocs,
  syncOnSessionStart,
  pushArchitectureDocs,
  autoPushOnEdit,
  SYNC_FILES,
  fireAutoReindex,
} = require('../cli/knowledge-sync');
const { request } = require('../cli/http');
const archCache = require('../mcp/architecture-cache');
const { isPlaceholderDescription } = require('../mcp/tag-description');
const { runHeadlessClaude } = require('./headless-claude');

const OPUS_MODEL = 'claude-opus-5';
const DOC_BATCH_SIZE = 6;
const TAG_BATCH_SIZE = 30;
const DOC_SLICE_CHARS = 3000;
const CONCURRENCY = 3;
const OPUS_TIMEOUT_MS = 120000;
const MAX_SAMPLE_TITLES = 8;

// Blank/null is always in-scope; a real "Auto-registered..." placeholder is the mirrored
// C1038 rule (ai/todo/server/src/mcp/tag-description.js, kept in sync with
// api/src/lib/tag-descriptions.js — separate npm packages, deliberate copy not a shared import).
function isPlaceholder(desc) {
  if (!desc || !String(desc).trim()) return true;
  return isPlaceholderDescription(String(desc));
}

async function fetchKnowledgeFiles(baseUrl, projectId, token) {
  const { status, data } = await request(`${baseUrl}/api/projects/${projectId}/knowledge`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (status !== 200) throw new Error(`fetchKnowledgeFiles: HTTP ${status}`);
  return data.files || [];
}

// Bounded-concurrency map — no new dependency justified for ~15-30 batches/run.
async function mapLimit(items, limit, fn) {
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
}

function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

function extractJsonArray(parsed) {
  if (Array.isArray(parsed)) return parsed;
  if (parsed && Array.isArray(parsed.items)) return parsed.items;
  return [];
}

function sanitizeDescription(text) {
  if (typeof text !== 'string') return '';
  return text.replace(/^["'`]+|["'`]+$/g, '').replace(/\s+/g, ' ').trim().slice(0, 500);
}

async function describeDocBatch(entries, { cwd } = {}) {
  // entries: [{ name, content }] — name is the tt-* tag / file key, content is doc text
  const block = entries.map((e, i) =>
    `### Doc ${i + 1}: ${e.name}\n${e.content.slice(0, DOC_SLICE_CHARS)}`
  ).join('\n\n');
  const prompt = [
    'You are generating short reference descriptions for a codebase knowledge-base index.',
    'Another AI agent will read ONLY these descriptions (not the full docs) to decide which',
    'docs are relevant to a given coding task, then load the matching doc into context.',
    'For each doc below, write ONE sentence (max 200 chars) naming the concrete module/feature',
    'and what it covers, specific enough that an agent can judge relevance from the sentence',
    'alone. No marketing language, no "this document describes...".',
    '',
    'Output ONLY a JSON array: [{"name": "...", "description": "..."}] — one entry per doc, same names.',
    '',
    block,
  ].join('\n');
  const parsed = await runHeadlessClaude(prompt, { model: OPUS_MODEL, timeoutMs: OPUS_TIMEOUT_MS, parseJson: true, cwd });
  const arr = extractJsonArray(parsed);
  const byName = new Map(arr.filter(e => e && typeof e.name === 'string').map(e => [e.name, sanitizeDescription(e.description)]));
  return entries.map(e => ({ name: e.name, description: byName.get(e.name) || '' }));
}

async function describeTagBatch(entries, { cwd } = {}) {
  // entries: [{ name, sampleTitles: string[], existingDescription }]
  const block = entries.map((e, i) =>
    `${i + 1}. "${e.name}"${e.existingDescription && !isPlaceholder(e.existingDescription) ? ` (current: "${e.existingDescription}")` : ''} — used on tasks: ${
      e.sampleTitles.length ? e.sampleTitles.join(' | ') : '(no sample tasks)'
    }`
  ).join('\n');
  const prompt = [
    'You are generating short reference descriptions for task-tracker tags that have no',
    'architecture doc. Another AI agent will read ONLY these descriptions to decide which',
    'tags apply to a new task, inferring each tag\'s meaning from its name and the sample',
    'task titles that already use it.',
    'For each tag below, write ONE sentence (max 150 chars) describing what kind of work',
    'it marks. No marketing language.',
    '',
    'Output ONLY a JSON array: [{"name": "...", "description": "..."}] — one entry per tag, same names.',
    '',
    block,
  ].join('\n');
  const parsed = await runHeadlessClaude(prompt, { model: OPUS_MODEL, timeoutMs: OPUS_TIMEOUT_MS, parseJson: true, cwd });
  const arr = extractJsonArray(parsed);
  const byName = new Map(arr.filter(e => e && typeof e.name === 'string').map(e => [e.name, sanitizeDescription(e.description)]));
  return entries.map(e => ({ name: e.name, description: byName.get(e.name) || '' }));
}

// C1218 — the ONE definition of "what counts as stale". reindexKnowledge() (real run) and
// detectStaleDescriptions() (cheap check, no Opus, no writes — see below) both call this;
// neither classifies scope inline any more. Pure/sync: no I/O beyond the doc-file reads
// already required to know if a tt-* doc's H1 is placeholder.
//
// linkOnlyEntries (a tag whose description is fine but whose tags.knowledge_file_id link,
// migration 046, is missing/stale) deliberately do NOT push tagCount/fileCount up in the
// caller — they need no Opus call, so they can't justify auto-firing one on their own.
//
// linkConflicts (C1244) — mirrors backfill-kb-descriptions.js's --repair-tag-links
// "conflict" bucket: a linkBad tag whose expectedFileKey is already claimed by a
// DIFFERENT tag's knowledge_file_id. tags.knowledge_file_id is UNIQUE
// (uk_tags_knowledge_file), so POST /knowledge/reindex would just hit ER_DUP_ENTRY,
// degrade to a description-only UPDATE, and record a {type:'tag-link'} skip — no
// progress. These entries must NOT count as a link-only reason to fire a run (see
// linkOnlyCount vs linkConflictCount in detectStaleDescriptions below), or a genuinely
// unrepairable conflict would re-fire a run every cooldown window forever.
function classifyKnowledgeScope({ dbTags, knowledgeFiles, sysTags, rootPath, force = false, titlesByTag = new Map(), errors = [] }) {
  const sysByTag = new Map(sysTags.map(t => [t.tag, t]));
  // Which tag currently claims each knowledge_file_id, by file key — used to tell a
  // repairable link-only gap apart from one that would collide with another tag's link.
  const claimedBy = new Map(dbTags.filter(t => t.knowledgeFileKey).map(t => [t.knowledgeFileKey, t.name]));

  const ttDocEntries = [];    // { name(=tag), content, filePath, fileKey }
  const plainTagEntries = []; // { name, existingDescription, sampleTitles }
  const coreFileEntries = []; // { name(=fileKey), content, fileKey }
  const linkOnlyEntries = []; // { name, description, fileKey } — description already good, only the DB link needs repair
  const linkConflicts = [];   // { name, fileKey, claimedBy } — expected doc already linked to a different tag; report-only, never auto-repaired

  for (const t of dbTags) {
    const dbBad = isPlaceholder(t.description);
    if (t.name.startsWith('tt-')) {
      const sys = sysByTag.get(t.name);
      // A tag with no local doc has no H1 to be bad — treat it as "not h1-bad" instead of
      // "always h1-bad" (the old `!sys ||` short-circuit), so a doc-less tag with an
      // already-good DB description is correctly skipped by the guard below instead of
      // being silently re-described from task titles on every single run, force or not.
      // Mirrors how `linkBad` (below) already treats "no doc" as "not bad" via
      // expectedFileKey being undefined. Zero behavior change for the ~93 tags that DO
      // have a matching doc: `!!sys && X` === the old `false || X` === X there.
      const h1Bad = !!sys && isPlaceholder(sys.description);
      // tags.knowledge_file_id (046) drifts independently of description quality — a
      // tag can have a perfectly good description while its DB link to the doc is
      // missing or stale (e.g. backfilled from an old name-match that no longer holds,
      // or never set because the tag predates 046). Re-index repairs that too.
      const expectedFileKey = sys ? `ai/architecture/${sys.file}` : undefined;
      const linkBad = expectedFileKey !== undefined && t.knowledgeFileKey !== expectedFileKey;
      // A claimed conflict can never be auto-repaired (see header comment) — but the tag
      // must still be PROCESSED (not skipped by the guard below) so the conflict itself
      // gets recorded into linkConflicts for reporting; it only stays out of the "repair
      // this" buckets (linkOnlyEntries/ttDocEntries via a link write).
      const claimant = expectedFileKey !== undefined ? claimedBy.get(expectedFileKey) : undefined;
      const linkClaimed = linkBad && claimant !== undefined && claimant !== t.name;
      if (!force && !dbBad && !h1Bad && !linkBad) continue; // description + doc H1 + DB link all already good
      if (sys) {
        if (dbBad || h1Bad || force) {
          const filePath = path.join(rootPath, 'ai', 'architecture', sys.file);
          let content = '';
          try { content = fs.readFileSync(filePath, 'utf8'); } catch (err) { errors.push(`read ${sys.file}: ${err.message}`); continue; }
          ttDocEntries.push({ name: t.name, content, filePath, fileKey: expectedFileKey });
        } else if (linkClaimed) {
          linkConflicts.push({ name: t.name, fileKey: expectedFileKey, claimedBy: claimant });
        } else {
          // Only the link is broken — description already reads fine, no Opus call needed.
          linkOnlyEntries.push({ name: t.name, description: t.description, fileKey: expectedFileKey });
        }
      } else {
        // DB has a tt-* tag with no matching doc file — describe it like a plain tag.
        plainTagEntries.push({ name: t.name, existingDescription: t.description, sampleTitles: titlesByTag.get(t.name) || [] });
      }
    } else {
      if (!force && !dbBad) continue;
      plainTagEntries.push({ name: t.name, existingDescription: t.description, sampleTitles: titlesByTag.get(t.name) || [] });
    }
  }

  // Core KB files (CLAUDE.md, AGENTS.md, GENERAL.md, CONVENTIONS.md) — same blank/
  // placeholder scoping, driven by the DB row (GET /knowledge now returns description).
  const filesByKey = new Map(knowledgeFiles.map(f => [f.file_key, f]));
  for (const fileKey of SYNC_FILES) {
    const row = filesByKey.get(fileKey);
    if (!force && row && !isPlaceholder(row.description)) continue;
    const filePath = path.join(rootPath, fileKey);
    let content = '';
    try { content = fs.readFileSync(filePath, 'utf8'); } catch { continue; } // not present locally — nothing to describe
    coreFileEntries.push({ name: fileKey, content, fileKey });
  }

  return { ttDocEntries, plainTagEntries, coreFileEntries, linkOnlyEntries, linkConflicts };
}

// Extracted from reindexKnowledge()'s old inline loop — builds the per-tag sample-titles
// map used ONLY for the plain-tag Opus prompt payload (never for scope membership), so
// detectStaleDescriptions() can skip calling this entirely (it never fetches tasks).
function buildTitlesByTag(tasks) {
  const titlesByTag = new Map();
  for (const t of tasks) {
    if (!Array.isArray(t.tags)) continue;
    for (const tagName of t.tags) {
      if (!titlesByTag.has(tagName)) titlesByTag.set(tagName, []);
      const list = titlesByTag.get(tagName);
      if (list.length < MAX_SAMPLE_TITLES && t.title) list.push(t.title);
    }
  }
  return titlesByTag;
}

/**
 * C1218 — cheap staleness check: exactly the two GET reads reindexKnowledge() needs to
 * decide scope (backend.getTagsDetailed(), the knowledge-files list) plus the local
 * archCache read. NO presync, NO backend.getTasksUnfiltered(), NO Opus call, NO writes —
 * safe to call on every sync trigger (WS connect, task spawn, window bind) without
 * costing more than two small HTTP GETs.
 *
 * @param {object} opts
 * @param {object} opts.backend
 * @param {string} opts.rootPath
 * @param {string} opts.baseUrl
 * @param {number|string} opts.projectId
 * @param {string} opts.token
 * @param {boolean} [opts.force]
 * @returns {Promise<{tagCount:number, fileCount:number, staleCount:number,
 *   linkOnlyCount:number, linkConflictCount:number, hasStale:boolean, needsRun:boolean,
 *   dbTags:Array, knowledgeFiles:Array, sysTags:Array, scope:object, errors:string[]}>}
 */
async function detectStaleDescriptions({ backend, rootPath, baseUrl, projectId, token, force = false }) {
  const errors = [];
  const [dbTags, knowledgeFiles] = await Promise.all([
    // Deliberately NOT catch-wrapped — a swallowed tag-list failure must not read as
    // "nothing is stale"; let it reject so the caller's guard treats this as a failed
    // detect (5-min damper), not a false "clean" (which would arm the full cooldown).
    backend.getTagsDetailed(),
    fetchKnowledgeFiles(baseUrl, projectId, token).catch(err => { errors.push(`list knowledge files: ${err.message}`); return []; }),
  ]);
  const sysTags = archCache.listSystemTags(rootPath);
  const scope = classifyKnowledgeScope({ dbTags, knowledgeFiles, sysTags, rootPath, force, errors });
  const tagCount = scope.ttDocEntries.length + scope.plainTagEntries.length;
  // A tt-* doc entry writes BOTH stores (H1 + DB), so it counts toward both tagCount and
  // fileCount — matches how the real run's tagsUpdated/filesUpdated end up looking.
  const fileCount = scope.coreFileEntries.length + scope.ttDocEntries.length;
  const linkOnlyCount = scope.linkOnlyEntries.length;
  const linkConflictCount = scope.linkConflicts.length;
  if (linkConflictCount > 0) {
    // Visible-but-non-blocking — same discipline as the module's other `errors` reporting.
    // These can never be auto-repaired (see classifyKnowledgeScope's header comment), so a
    // silent drop would hide a real, permanently-stuck DB state from anyone watching stderr.
    process.stderr.write(`[kb-reindex] ${linkConflictCount} tt-* tag(s) can't auto-link — expected doc already linked to a different tag: ${scope.linkConflicts.map(c => `${c.name} (wants ${c.fileKey}, held by ${c.claimedBy})`).join(', ')}\n`);
  }
  return {
    tagCount,
    fileCount,
    staleCount: scope.ttDocEntries.length + scope.plainTagEntries.length + scope.coreFileEntries.length,
    linkOnlyCount,
    linkConflictCount,
    hasStale: tagCount + fileCount > 0,
    // C1244 — "needs a run at all", broader than hasStale ("needs Opus"). A link-only gap
    // (tags.knowledge_file_id NULL/stale, description already fine) costs zero Opus calls
    // to repair, so it must still trigger reindexKnowledge() even when nothing is stale —
    // see fireAutoReindex's use of this flag in knowledge-sync.js.
    needsRun: tagCount + fileCount > 0 || linkOnlyCount > 0,
    dbTags, knowledgeFiles, sysTags, scope, errors,
  };
}

/**
 * @param {object} opts
 * @param {string} opts.baseUrl
 * @param {number|string} opts.projectId
 * @param {string} opts.token
 * @param {string} opts.rootPath - project root (KB files live under here)
 * @param {object} opts.backend - the active task backend (api-backend.js instance)
 * @param {(p: {phase: string, done: number, total: number}) => void} [opts.onProgress]
 * @param {boolean} [opts.force] - re-describe even already-good descriptions
 * @param {boolean} [opts.dryRun] - skip the presync + all writes (disk, push, DB); still
 *   runs real Opus batches so `proposals` reflects what a live run would produce. For
 *   `scripts/probe-kb-reindex.js --dry-run` — verification without touching anything.
 * @returns {Promise<{ tagsUpdated: number, filesUpdated: number, skipped: number,
 *   errors: string[], proposals: { tags: Array<{name,description}>, files: Array<{file_key,description}> } }>}
 */
async function reindexKnowledge({ baseUrl, projectId, token, rootPath, backend, onProgress = () => {}, force = false, dryRun = false }) {
  const errors = [];
  const progress = (phase, done, total) => { try { onProgress({ phase, done, total }); } catch { /* never let a bad listener break the run */ } };

  // 1. Sync first — analysis must run against current disk == current remote, same
  // sequence the Knowledge Base > Sync handler runs (ws-handlers.js 'sync-kb'). Skipped
  // in dryRun — pull/push mutate local disk + remote, which a dry run must never do.
  progress('sync', 0, 1);
  if (!dryRun) {
    await pullArchitectureDocs(baseUrl, projectId, token, rootPath);
    await syncOnSessionStart(baseUrl, projectId, token, rootPath);
    await pushArchitectureDocs(baseUrl, projectId, token, rootPath);
  }
  progress('sync', 1, 1);

  // 2. Build the work list. C1218 — scope classification now lives in ONE place
  // (classifyKnowledgeScope, called via detectStaleDescriptions) so the real run and the
  // cheap auto-trigger check can never disagree about what counts as stale.
  const [detected, tasks] = await Promise.all([
    detectStaleDescriptions({ backend, rootPath, baseUrl, projectId, token, force }),
    backend.getTasksUnfiltered().catch(err => { errors.push(`list tasks: ${err.message}`); return []; }),
  ]);
  errors.push(...detected.errors);
  const { dbTags, knowledgeFiles } = detected;
  const titlesByTag = buildTitlesByTag(tasks);
  for (const e of detected.scope.plainTagEntries) e.sampleTitles = titlesByTag.get(e.name) || [];
  const { ttDocEntries, plainTagEntries, coreFileEntries, linkOnlyEntries } = detected.scope;

  const docBatches = chunk(ttDocEntries, DOC_BATCH_SIZE).map(entries => ({ kind: 'tt-doc', entries }));
  const coreBatches = chunk(coreFileEntries, DOC_BATCH_SIZE).map(entries => ({ kind: 'core-file', entries }));
  const tagBatches = chunk(plainTagEntries, TAG_BATCH_SIZE).map(entries => ({ kind: 'plain-tag', entries }));
  const allBatches = [...docBatches, ...coreBatches, ...tagBatches];

  if (allBatches.length === 0 && linkOnlyEntries.length === 0) {
    return { tagsUpdated: 0, filesUpdated: 0, skipped: dbTags.length, errors, proposals: { tags: [], files: [] } };
  }

  let batchesDone = 0;
  progress('analyze', 0, allBatches.length);

  // 3. Batched Opus calls — tt-* docs, core files, plain tags. Bounded concurrency.
  const tagResults = new Map();  // name -> description
  const fileResults = new Map(); // fileKey -> description
  const changedDocFiles = [];    // { filePath, fileKey, tagName, description }
  const linkByTagName = new Map(ttDocEntries.map(e => [e.name, e.fileKey])); // repaired alongside description for these

  await mapLimit(allBatches, CONCURRENCY, async (batch) => {
    try {
      if (batch.kind === 'plain-tag') {
        const results = await describeTagBatch(batch.entries, { cwd: rootPath });
        for (const r of results) if (r.description) tagResults.set(r.name, r.description);
      } else {
        const results = await describeDocBatch(batch.entries.map(e => ({ name: e.name, content: e.content })), { cwd: rootPath });
        for (const r of results) {
          if (!r.description) continue;
          if (batch.kind === 'tt-doc') {
            tagResults.set(r.name, r.description);
            const entry = batch.entries.find(e => e.name === r.name);
            if (entry) {
              fileResults.set(entry.fileKey, r.description);
              changedDocFiles.push({ filePath: entry.filePath, fileKey: entry.fileKey, tagName: entry.name, description: r.description });
            }
          } else {
            fileResults.set(r.name, r.description);
          }
        }
      }
    } catch (err) {
      errors.push(`${batch.kind} batch: ${err.message}`);
    }
    batchesDone++;
    progress('analyze', batchesDone, allBatches.length);
  });

  const filesPayload = [...fileResults.entries()].map(([file_key, description]) => ({ file_key, description }));
  // tagsPayload: Opus-described tags (file_key attached when this tag has a doc match),
  // plus linkOnlyEntries — description already good, sent through unchanged purely to
  // carry the file_key that repairs tags.knowledge_file_id (046).
  const tagsPayload = [
    ...[...tagResults.entries()].map(([name, description]) => {
      const fileKey = linkByTagName.get(name);
      return fileKey ? { name, description, file_key: fileKey } : { name, description };
    }),
    ...linkOnlyEntries.map(({ name, description, fileKey }) => ({ name, description, file_key: fileKey })),
  ];

  if (dryRun) {
    // Real Opus output computed above; every write (disk, push, DB) skipped.
    progress('write-docs', 0, 0);
    progress('persist', 0, 0);
    return { tagsUpdated: 0, filesUpdated: 0, skipped: 0, errors, proposals: { tags: tagsPayload, files: filesPayload } };
  }

  // 4. Rewrite the H1 line of every changed tt-*.md, push, invalidate cache — so
  // list_system_tags stops serving stale text immediately, not on next Sync.
  progress('write-docs', 0, changedDocFiles.length);
  const pushedKeys = [];
  for (let i = 0; i < changedDocFiles.length; i++) {
    const { filePath, fileKey, tagName, description } = changedDocFiles[i];
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      const rewritten = content.replace(/^#[^#\n].*$/m, `# ${tagName} — ${description}`);
      if (rewritten !== content) {
        fs.writeFileSync(filePath, rewritten, 'utf8');
        // C1490 — re-index is a boot/manual operation, not "as you go" traffic; its own
        // H1-rewrite push must land even with Sync-as-you-go off.
        const pushResult = await autoPushOnEdit(filePath, rootPath, { ignoreSyncFlag: true });
        if (pushResult && pushResult.ok === false) errors.push(`push ${fileKey}: ${pushResult.message || pushResult.status}`);
        pushedKeys.push(fileKey);
      }
    } catch (err) {
      errors.push(`rewrite ${fileKey}: ${err.message}`);
    }
    progress('write-docs', i + 1, changedDocFiles.length);
  }
  if (pushedKeys.length) archCache.invalidateArchForKeys(pushedKeys, rootPath);

  // 5. Persist the DB store — one bulk call (api/src/routes/knowledge.js POST .../reindex).
  progress('persist', 0, 1);
  let tagsUpdated = 0;
  let filesUpdated = 0;
  let skippedCount = 0;
  if (filesPayload.length || tagsPayload.length) {
    try {
      const result = await backend.reindexKnowledge({ files: filesPayload, tags: tagsPayload });
      tagsUpdated = result.tags_updated || 0;
      filesUpdated = result.files_updated || 0;
      skippedCount = (result.skipped || []).length;
    } catch (err) {
      errors.push(`persist: ${err.message}`);
    }
  }
  progress('persist', 1, 1);

  return { tagsUpdated, filesUpdated, skipped: skippedCount, errors, proposals: { tags: tagsPayload, files: filesPayload } };
}

// C1230 — has this project EVER completed a re-index pass? Backed by
// `projects.kb_last_reindexed_at` (C1229, migration 050), read via
// `backend.getProjectSettings()` (`GET /api/projects/:id` — NOT the knowledge-file list,
// which carries no such column). Never throws. Fails CLOSED: anything short of a
// definitively-fetched row with a definitively-null stamp reads as "already indexed", so
// an offline backend / file backend / stale pre-050 API can never mistakenly force-fire an
// expensive Opus run. {refresh:true} bypasses api-backend.js's 30s cache so a stamp another
// trigger just wrote is seen immediately, not up to 30s later.
async function hasNeverBeenReindexed(backend) {
  if (!backend || typeof backend.getProjectSettings !== 'function') return false;
  const project = await backend.getProjectSettings({ refresh: true }).catch(() => null);
  if (!project) return false; // offline / file backend / no creds — getProjectSettings never throws, just returns null
  if (!('kb_last_reindexed_at' in project)) return false; // API predates migration 050
  return project.kb_last_reindexed_at == null; // ISO string over HTTP, or null/undefined
}

/**
 * C1230 — the once-per-project forced run. Call only after hasNeverBeenReindexed(backend)
 * is true (kb-auto-reindex.js's fireAutoReindexWithBroadcast is the one production caller
 * and does that check itself). `manual:true` bypasses fireAutoReindex's damper/lease/
 * cooldown/hasStale gate; `force:false` keeps Opus scoped to genuinely blank/placeholder
 * entries — NOT a full re-describe of every tag/doc (that's a materially more expensive,
 * deliberately separate strength — see tt-knowledge-sync.md § Force-Once).
 *
 * reindexKnowledge() only POSTs (and the API only stamps kb_last_reindexed_at) when there
 * is something to write (see its early-return when allBatches/linkOnlyEntries are both
 * empty, and the filesPayload.length||tagsPayload.length guard around the persist call).
 * A healthy project would therefore never get stamped and would re-attempt this force run
 * on every single trigger forever — so when the real run didn't write anything, this fires
 * one stamp-only `backend.reindexKnowledge({files:[],tags:[]})`: an empty payload still
 * passes the API's per-entry validation, opens the transaction, and hits the C1229
 * unconditional stamp (api/src/routes/knowledge.js) with zero rows updated.
 *
 * @param {object} opts
 * @param {object} opts.backend
 * @param {string} opts.rootPath
 * @param {string} [opts.label] - trigger tag for fireAutoReindex's logs/state
 * @param {(d:object)=>void} [opts.onStart]
 * @param {(p:object)=>void} [opts.onProgress]
 * @param {Function} [opts.runReindex] - TEST SEAM ONLY, forwarded to fireAutoReindex — no
 *   production call site passes this.
 * @returns {Promise<{status:string, ok:boolean, result?:object, stamped:boolean, message?:string}>}
 */
async function forceReindexOnStartup({ backend, rootPath, label = 'force-once', onStart, onProgress, runReindex } = {}) {
  if (!(await hasNeverBeenReindexed(backend))) {
    return { status: 'skipped-already-indexed', ok: true, stamped: false };
  }

  const res = await fireAutoReindex(rootPath, label, { backend, manual: true, force: false, onStart, onProgress, runReindex });

  const wroteSomething = res.status === 'ran' && res.result
    && ((res.result.tagsUpdated || 0) + (res.result.filesUpdated || 0) > 0);
  // Only stamp-only when the run actually completed (ran/joined) without writing anything —
  // a skipped/error status (e.g. skipped-no-creds, detect-failed) means the real cause is
  // still unfixed and must not be papered over with a stamp that hides it from every future
  // trigger. 'joined' means another in-flight run (also manual:true) already stamped or will.
  let stamped = false;
  if (res.status === 'ran' && res.ok && !wroteSomething) {
    try {
      await backend.reindexKnowledge({ files: [], tags: [] });
      stamped = true;
    } catch (err) {
      return { status: 'stamp-failed', ok: false, result: res.result, stamped: false, message: err.message };
    }
  }

  return { status: res.status, ok: res.ok, result: res.result, stamped, message: res.message };
}

module.exports = { reindexKnowledge, detectStaleDescriptions, hasNeverBeenReindexed, forceReindexOnStartup };
