require('./scripts/check-node-version.js');
const esbuild = require('esbuild');
const fs = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');

const WATCH = process.argv.includes('--watch');
const ELECTRON_DEV = process.argv.includes('--electron-dev');
const SRC = path.join(__dirname, 'src', 'client');
const DIST = path.join(__dirname, 'dist');
const ASSETS = path.join(__dirname, 'assets');
const PI_BRIDGE_ENTRY = path.join(__dirname, 'src', 'server', 'providers', 'pi-ext', 'mcp-bridge.mjs');

function copyTemplate() {
  fs.copyFileSync(
    path.join(SRC, 'template.html'),
    path.join(DIST, 'todo.html')
  );
  console.log('  dist/todo.html');
}

function copyMarked() {
  fs.copyFileSync(
    require.resolve('marked/marked.min.js'),
    path.join(DIST, 'marked.min.js')
  );
  console.log('  dist/marked.min.js');
}

// Favicon sources are generated by scripts/gen-icon.js (TPT289); the build only copies them.
function copyFavicons() {
  for (const name of ['favicon.ico', 'favicon.svg']) {
    const src = path.join(ASSETS, name);
    if (!fs.existsSync(src)) continue;
    fs.copyFileSync(src, path.join(DIST, name));
    console.log(`  dist/${name}`);
  }
}

function launchElectron() {
  const electronBin = require('electron');
  const child = spawn(electronBin, ['.'], { stdio: 'inherit' });
  child.on('exit', () => process.exit(0));
}

// The Pi MCP bridge extension is staged outside app.asar (providers/pi-task-tools.js), where no
// node_modules exist, so the SDK is inlined. The banner gives bundled CommonJS dependencies a
// working require() inside the ESM output.
async function bundlePiExt(outfile = path.join(DIST, 'pi-ext', 'mcp-bridge.mjs')) {
  await esbuild.build({
    entryPoints: [PI_BRIDGE_ENTRY],
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node22',
    outfile,
    banner: { js: "import { createRequire as __bridgeCreateRequire } from 'node:module'; const require = __bridgeCreateRequire(import.meta.url);" },
    logLevel: 'warning',
  });
  console.log(`  ${path.relative(__dirname, outfile)}`);
  return outfile;
}

const htmlPlugin = {
  name: 'html-template',
  setup(build) {
    let electronLaunched = false;
    build.onEnd((result) => {
      copyTemplate();
      copyMarked();
      copyFavicons();
      if (ELECTRON_DEV && !electronLaunched && result.errors.length === 0) {
        electronLaunched = true;
        launchElectron();
      }
    });
  },
};

async function main() {
  fs.mkdirSync(DIST, { recursive: true });
  await bundlePiExt();
  const buildOptions = {
    entryPoints: [path.join(SRC, 'index.js')],
    bundle: true,
    format: 'iife',
    outdir: DIST,
    entryNames: 'bundle',
    loader: { '.css': 'css' },
    plugins: [htmlPlugin],
    logLevel: 'info',
  };

  if (WATCH || ELECTRON_DEV) {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();
    if (WATCH) {
      fs.watch(path.join(SRC, 'template.html'), () => {
        copyTemplate();
      });
      console.log('Watching for changes...');
    }
  } else {
    await esbuild.build(buildOptions);
  }
}

if (require.main === module) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

module.exports = { bundlePiExt };
